name: RedHCF
main: org.golde.bukkit.redhcf.Main
version: 1.0
author: Eric Golde
description: A custom plugin for XBoxKidYT
website: https://github.com/egold555/RedHCF/
commands:
   kit:
      description: Opens the kit menu
      usage: /kit 
      aliases: [kits, k]